const Layout = ({ children }) => {
  return (
    <div className="">
      {children}
      <footer className="w-full flex justify-center items-center  md:h-16 p-0 mt-2 ">
        <p className="text-mainGray text-[10px] md:text-md p-0">
          TemoGPT is integrated with the ChatGPT API to display results
          generated by it.
        </p>
      </footer>
    </div>
  );
};

export default Layout;
